name: CI


# Controls when the workflow will run on pushs
on:
  # Triggers the workflow on push or pull request events but only for the main branch 
  push:
    branches: 
      - test1
  pull_request:
    types: [closed]
    branches: 
      - uat
      - prod
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    uses: dhivya3107/dhivyapipeline/.github/workflows/pipeline.yml@pipe
